import random as r
import os
import sys
from time import sleep

def isIDLE():
   if "idlelib" in sys.modules:
      return True
   else:
      return False

def newscreen(n=105):
    print("\nLoading",end='')
    for i in range(3):
        sys.stdout.write('.')
        sys.stdout.flush()
        sleep(0.6)
    print()
    if isIDLE():
        print('-'*n)
    else:
        if os.name == 'posix':
            os.system('clear')
        else:
            os.system('cls')

def slowprint(s,t=0.035):
   for i in s:
      print(i,end='')
      if isIDLE():
         sleep(t)

slowprint('Welcome to MasterMind, The classic code-cracking game!\n',0.02)
print('-'*105)

slowprint('''1. The code-maker (Computer) will generate a 4 digit code (X X X X) based on the chosen level.
2. The code-breaker (You) has to break this code,
   by duplicating its exact digits and positions.
3. After every attempt,
   clues will be given on the left side of the board, indicated by 2 pegs:
\ti.  White Peg (W) - For every correct digit that is placed in the wrong position.
\tii. Red Peg (R)   - For every correct digit that is placed in the correct position as well.
4. A total of 10 attempts are allowed before the game is over, and the code is revealed.
5. The Aim of the game is to break the code with the least attempts.
''')
print('-'*105)

lvl = {1:6,2:7,3:8,4:9}
levelname = {1:"Easy",2:"Medium",3:"Difficult",4:"Insane"}
code,codedisp,plist,alist,op,counter=[],[],[],[],'',0
def initialize():
    global code,codedisp,plist,alist,op,counter
    code = []
    codedisp = ['X','X','X','X']
    plist = []
    alist = []
    op = ''
    for i in range(10):
        plist.append(['-','-','-','-'])
        alist.append(['-','-','-','-']) 
    counter = 0

def coder():
    global code,lvl,op
    choose = '''Choose your level:
1 - Easy
2 - Medium
3 - Difficult
4 - Insane

Enter your choice: '''
    while True:
      if op=='':
         slowprint(choose)
      else:
         slowprint(choose,0.004)
      op = int(input())
      if op not in [1,2,3,4]:
         print('-'*45)
         slowprint("ERROR")
         print("\n\nInvalid Choice! (Enter 1, 2, 3 or 4)")
         print('-'*45)
         sleep(1)
      else:
         break
    for i in range(4):
        code.append(r.choice([i for i in range(1,lvl[op])]))
    print('-'*45)
    slowprint("The code has been generated! Start Cracking!\n")

def board_rules():
    global codedisp
    print('-'*105)
    for i in plist:
        if i==['R','R','R','R']:
            codedisp = code
            
    print('┌───────┬─────┬─────┬─────┬─────┐')
    print('│ Code: │',end='')
    
    for i in codedisp:
        print(' ',i,' │',end='')
        
    print("\tRules of the game:")
    print('├───────┼─────┼─────┼─────┼─────┤')
    
    for i in range(1,11):
        
          print('│',plist[-i][0],' ',plist[-i][1],'│     │     │     │     │',end='')
          if i==1:
              print("\t1. Crack the 4 digit code (X X X X) generated by the computer.")
          elif i==3:
              print("\t\tXXXX")
          elif i==4:
              print("\t   the board, indicated by 2 pegs:")
          elif i==5:
              print("\t\t\tFor every correct digit that is")
          elif i==6:
              print("\t\tii. Red Peg (R) -")
          else:
              print()
              
          print('│',plist[-i][2],' ',plist[-i][3],'│',end='')
          
          for j in range(4):
              print(' ',alist[-i][j],' │',end='')
          if i==2:
              print("\t3. The attempts can be entered in any of the following formats:")
          elif i==5:
              print("\t\t\tplaced in the wrong position.")
          elif i==6:
              print("\t\t\tFor every correct digit that is")
          elif i==7:
              print("\t5. The order of these pegs does NOT matter.")
          else:
              print()

          if i==10:
              print('└───────┴─────┴─────┴─────┴─────┘')
          else:
              print('├───────┼─────┼─────┼─────┼─────┤',end='')
              if i==1:
                  print("\t2. Digits may or may not be be repeated.")
              elif i==2:
                  print("\t\tX X X X")
              elif i==3:
                  print("\t4. After every attempt, clues will be given on the left side of")
              elif i==4:
                  print("\t\ti.  White Peg (W) -")
              elif i==6:
                  print("\t\t\tplaced in the correct position as well.")
              else:
                  print()                
    print('-'*105)

def board():
    global codedisp
    print('-'*105)
    for i in plist:
        if i==['R','R','R','R']:
            codedisp = code        
    print('┌───────┬─────┬─────┬─────┬─────┐')
    print('│ Code: │',end='')
    for i in codedisp:
        print(' ',i,' │',end='')
    print('\n├───────┼─────┼─────┼─────┼─────┤')
    for i in range(1,11):   
          print('│',plist[-i][0],' ',plist[-i][1],'│     │     │     │     │')  
          print('│',plist[-i][2],' ',plist[-i][3],'│',end='')    
          for j in range(4):
              print(' ',alist[-i][j],' │',end='')
          print()
          if i==10:
              print('└───────┴─────┴─────┴─────┴─────┘')
          else:
              print('├───────┼─────┼─────┼─────┼─────┤')           
    print('-'*105)
    
def breaker():
    global alist, plist
    pegs = ['-','-','-','-']
    while True:
        slowprint("\nYour Attempt: ",0.02)
        attempt = [int(i) for i in input().split()]
        if not len(attempt)==4:
            print("\nInvalid Attempt! Please enter exactly 4 digits!")
        else:
            for i in attempt:
                if not type(i)==type(1):
                    print("\nInvalid Attempt! Please enter digits only!")
                    break
            alist[counter-1]=attempt
            break
    for i in range(4):
        if attempt[i] in code:
            if attempt[i]==code[i]:
                pegs[i] = 'R'
            else:
                pegs[i] = 'W'
    r.shuffle(pegs)
    for i in range(4):
        if pegs[i]=='-':
            pegs=list('-')+pegs[:i]+pegs[i+1:]
    plist[counter-1]=pegs

def play():
    global codedisp,counter
    coder()
    print(code) #REMOVE
    while True:
        if code in alist:
            newscreen()
            board()
            slowprint("Congratulations! You cracked the code!\n")
            newscreen()
            break
        elif counter==10:
            newscreen()
            codedisp = code
            board()
            slowprint('''Sorry, you have lost!
The correct code is displayed on the board!
''')
            newscreen()
            break
        counter+=1
        newscreen()
        board_rules()
        print('Level - ',levelname[op],'\nThe code can have the following digits:\n',[i for i in range(1,lvl[op])],sep='')
        print('-'*105)
        slowprint("Attempt "+str(counter)+"\n")
        breaker()

f='y'
ynl = ['y','ye','yes','yep','yeah','yas','yus','yee','n','no','nope','na','nah']
while True:
    initialize()
    play()
    while True:
        slowprint("Do you want to play again? (y/n): ")
        f = input().lower().strip()
        if f in ynl:
            break
        else:
            slowprint("\nERROR\n\n")      
    if f in ynl[:8]:
        newscreen()
        continue
    else:
        newscreen()
        slowprint("Thank you for playing MasterMind!")
        sleep(5)
        break
